spring.application.name=appburnbook

server.port=8081

spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:42543/railway
spring.datasource.username=root
spring.datasource.password=qEynOKsvYAxJkaoZrBFTLVOKESdwzzRO
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=NjgoHSx41QmJTcmcTZc753CnFHUuyameto37wZQEp9M
jwt.expiration=86400000